[package]
name = "coursera-prometheus-starter"
version = "0.1.0"
edition = "2024"

[dependencies]
nlprule = "0.6.4"
regex = "1.11.1"
serde_json = "1.0.140"
serde = { version = "1", features = ["derive"] }
actix-web = "4"
psutil = "3.2.1"
actix-web-prom = "0.9.0"
